export const DEFAULT_CATEGORIES = [
  'Dairy',
  'Fruits',
  'Vegetables',
  'Grains & Cereals',
  'Pulses & Dals',
  'Oils & Ghee',
  'Snacks',
  'Beverages',
  'Tea & Coffee',
  'Spices & Condiments',
  'Sauces & Spreads',
  'Meat & Seafood',
  'Bakery',
  'Frozen Foods',
  'Dry Fruits & Nuts',
  'Breakfast & Cereals',
  'Chocolates & Sweets',
  'Personal Care',
  'Baby Care',
  'Health & Wellness',
  'Household',
  'Cleaning Supplies',
  'Pet Care',
  'Kitchen & Home',
  'Other',
];

export const UNITS_OF_MEASUREMENT = [
  { label: 'Kilograms (kg)', value: 'kg' },
  { label: 'Grams (g)', value: 'g' },
  { label: 'Milligrams (mg)', value: 'mg' },
  { label: 'Litres (L)', value: 'L' },
  { label: 'Millilitres (mL)', value: 'mL' },
  { label: 'Pieces (pcs)', value: 'pcs' },
  { label: 'Number (Nos)', value: 'nos' },
  { label: 'Dozen (dz)', value: 'dz' },
  { label: 'Packets (pkt)', value: 'pkt' },
  { label: 'Pouch', value: 'pouch' },
  { label: 'Sachet', value: 'sachet' },
  { label: 'Bottles (btl)', value: 'btl' },
  { label: 'Jar', value: 'jar' },
  { label: 'Tube', value: 'tube' },
  { label: 'Boxes (box)', value: 'box' },
  { label: 'Cans (can)', value: 'can' },
  { label: 'Bags (bag)', value: 'bag' },
  { label: 'Bunch', value: 'bunch' },
  { label: 'Tray', value: 'tray' },
  { label: 'Roll', value: 'roll' },
  { label: 'Strip', value: 'strip' },
  { label: 'Pair', value: 'pair' },
  { label: 'Set', value: 'set' },
];

export const CONSUMPTION_FREQUENCIES = [
  { label: 'Daily', value: 'daily' },
  { label: 'Weekly', value: 'weekly' },
  { label: 'Monthly', value: 'monthly' },
];

export const ONBOARDING_TEMPLATES = [
  { name: 'Rice', category: 'Grains & Cereals', unit: 'kg', defaultQuantity: 5, threshold: 1 },
  { name: 'Wheat Flour (Atta)', category: 'Grains & Cereals', unit: 'kg', defaultQuantity: 5, threshold: 1 },
  { name: 'Milk', category: 'Dairy', unit: 'L', defaultQuantity: 2, threshold: 0.5 },
  { name: 'Eggs', category: 'Dairy', unit: 'pcs', defaultQuantity: 12, threshold: 3 },
  { name: 'Cooking Oil', category: 'Spices & Condiments', unit: 'L', defaultQuantity: 2, threshold: 0.5 },
  { name: 'Sugar', category: 'Grains & Cereals', unit: 'kg', defaultQuantity: 2, threshold: 0.5 },
  { name: 'Salt', category: 'Spices & Condiments', unit: 'kg', defaultQuantity: 1, threshold: 0.25 },
  { name: 'Tea', category: 'Beverages', unit: 'g', defaultQuantity: 250, threshold: 50 },
  { name: 'Coffee', category: 'Beverages', unit: 'g', defaultQuantity: 200, threshold: 50 },
  { name: 'Bread', category: 'Bakery', unit: 'pkt', defaultQuantity: 1, threshold: 0 },
  { name: 'Butter', category: 'Dairy', unit: 'g', defaultQuantity: 500, threshold: 100 },
  { name: 'Onions', category: 'Vegetables', unit: 'kg', defaultQuantity: 2, threshold: 0.5 },
  { name: 'Tomatoes', category: 'Vegetables', unit: 'kg', defaultQuantity: 1, threshold: 0.25 },
  { name: 'Potatoes', category: 'Vegetables', unit: 'kg', defaultQuantity: 2, threshold: 0.5 },
  { name: 'Bananas', category: 'Fruits', unit: 'dz', defaultQuantity: 1, threshold: 0 },
];

export const ALERT_FREQUENCIES = [
  { label: 'Daily', value: 'daily' },
  { label: 'Every 2 days', value: 'every_2_days' },
  { label: 'Weekly', value: 'weekly' },
  { label: 'Never', value: 'never' },
];
